
- name: "Quan Catering"
  address: "222 02ND ST"
  longitude: -122.398235074249
  latitude: 37.786319798284
  location_description: "02ND ST: HOWARD ST to TEHAMA ST (200 - 227)"
  facility_type: "Truck"
  food_items:
   "Cold Truck: Soft drinks: cup cakes: potato chips: cookies: gum: sandwiches (hot & cold): peanuts: muffins: coff (hot & cold): water: juice: yoplait: milk: orange juice: sunflower seeds: can foods: burritos: buscuits: chimichangas: rice krispies"

- name: "Paradise Catering"
  address: "19 CLEMENTINA ST"
  longitude: -122.395447605152
  latitude: 37.787157744174
  location_description: "CLEMENTINA ST: 01ST ST to ECKER ST (1 - 37)"
  facility_type: "Truck"
  food_items: "Cold Truck: Sandwiches: snacks: prepackaged items: beverages:"

- name: "Paradise Catering"
  address: "575 HARRISON ST"
  longitude: -122.394380639101
  latitude: 37.7844204919929
  location_description: "HARRISON ST: ESSEX ST \\ I-80 E ON RAMP to 02ND ST (550 - 599)"
  facility_type: "Truck"
  food_items: "Cold Truck: Sandwiches: snacks: prepackaged items: beverages:"

- name: "Mini Mobile Food Catering"
  address: "245 01ST ST"
  longitude: -122.394594036205
  latitude: 37.7879000978181
  location_description: "01ST ST: CLEMENTINA ST to FOLSOM ST (245 - 299)"
  facility_type: "Truck"
  food_items: "Cold Truck: Corn Dogs: Noodle Soups: Candy: Pre-packaged Snacks: Sandwiches: Chips: Coffee: Tea: Various Beverages"

- name: "Senor Sisig"
  address: "120 02ND ST"
  longitude: -122.399566331429
  latitude: 37.7875140607381
  location_description: "02ND ST: MISSION ST to MINNA ST (100 - 130)"
  facility_type: "Truck"
  food_items: "Filipino fusion food: taco: burrito: nachos: rice plates"

- name: "Curbside Coffee"
  address: "124 FOLSOM ST"
  longitude: -122.391392669926
  latitude: 37.7900747773418
  location_description: "SPEAR ST: HOWARD ST to FOLSOM ST (200 - 299)"
  facility_type: "Push Cart"
  food_items: "Cold Truck: Sandwiches: snacks: prepackaged items: beverages:"

- name: "Liang Bai Ping"
  address: "201 FOLSOM ST"
  longitude: -122.391181920263
  latitude: 37.7881452832928
  location_description: "MAIN ST: FOLSOM ST to HARRISON ST (300 - 399)"
  facility_type: "Truck"
  food_items: "Cold Truck: Sandwiches: snacks: prepackaged items: beverages:"